# Generated by Django 4.2.7 on 2026-09-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('system', '跟随系统')], default='system', max_length=16, verbose_name='主题')),
                ('font_size', models.CharField(choices=[('small', '小'), ('normal', '标准'), ('large', '大')], default='normal', max_length=16, verbose_name='字号')),
                ('bubble_style', models.CharField(choices=[('classic', '经典'), ('compact', '紧凑')], default='classic', max_length=16, verbose_name='气泡样式')),
                ('notify_sound', models.BooleanField(default=True, verbose_name='提示音')),
                ('notify_desktop', models.BooleanField(default=False, verbose_name='桌面通知')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
            },
        ),
    ]
