# Generated by Django 4.2.7 on 2026-09-12 14:04

import backend.chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=backend.chat.models.attachment_upload_to, verbose_name='文件')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=backend.chat.models.thumb_upload_to, verbose_name='缩略图')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('size', models.BigIntegerField(default=0, verbose_name='大小(字节)')),
                ('mime', models.CharField(blank=True, max_length=100, verbose_name='MIME 类型')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA256')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('direct', '单聊'), ('group', '群聊')], default='direct', max_length=16, verbose_name='类型')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='名称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='conversation_avatars/%Y%m/', verbose_name='会话头像')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后消息时间')),
                ('last_seq', models.BigIntegerField(default=0, verbose_name='当前最大序号')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='群主')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.BigIntegerField(verbose_name='会话内序号')),
                ('kind', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('system', '系统消息')], default='text', max_length=16, verbose_name='类型')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('client_msg_id', models.CharField(blank=True, max_length=64, verbose_name='客户端消息ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.attachment', verbose_name='附件')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='会话')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='引用消息')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_messages', to=settings.AUTH_USER_MODEL, verbose_name='撤回人')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['conversation_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '群主'), ('admin', '管理员'), ('member', '成员')], default='member', max_length=16, verbose_name='角色')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
                ('last_read_seq', models.BigIntegerField(default=0, verbose_name='已读序号')),
                ('unread_count', models.IntegerField(default=0, verbose_name='未读数')),
                ('is_muted', models.BooleanField(default=False, verbose_name='免打扰')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.conversation', verbose_name='会话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会话成员',
                'verbose_name_plural': '会话成员',
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='已读时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='chat.message', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reads', to=settings.AUTH_USER_MODEL, verbose_name='读者')),
            ],
            options={
                'verbose_name': '已读回执',
                'verbose_name_plural': '已读回执',
                'indexes': [models.Index(fields=['message', 'user'], name='chat_messag_message_c52fd1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='messageread',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='uniq_message_read'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'seq'], name='chat_messag_convers_c897c6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='uniq_message_seq'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', '-is_pinned'], name='chat_member_user_id_3c97c2_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['conversation', 'role'], name='chat_member_convers_0a9735_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='uniq_membership'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='chat_conver_last_me_31163c_idx'),
        ),
    ]
