# Generated by Django 4.2.7 on 2026-09-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='管理员移除时间'),
        ),
        migrations.AddField(
            model_name='message',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_messages', to=settings.AUTH_USER_MODEL, verbose_name='移除操作人'),
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='理由')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理'), ('dismissed', '已驳回')], default='pending', max_length=16, verbose_name='状态')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='举报时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message', verbose_name='被举报消息')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
            ],
            options={
                'verbose_name': '消息举报',
                'verbose_name_plural': '消息举报',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['status', '-created'], name='chat_messag_status_49c7ac_idx'), models.Index(fields=['message'], name='chat_messag_message_88b1d3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(fields=('reporter', 'message'), name='uniq_report_per_user_message'),
        ),
    ]
