# Generated by Django 4.2.7 on 2026-09-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user.ban', '禁用用户'), ('user.unban', '解禁用户'), ('user.revoke_tokens', '强制下线'), ('message.remove', '移除消息'), ('report.resolve', '举报结案'), ('report.dismiss', '举报驳回'), ('conversation.view', '查看会话')], max_length=32, verbose_name='动作')),
                ('target_type', models.CharField(blank=True, max_length=32, verbose_name='对象类型')),
                ('target_id', models.BigIntegerField(blank=True, null=True, verbose_name='对象 id')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='说明')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '管理员操作日志',
                'verbose_name_plural': '管理员操作日志',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['actor', '-created'], name='ops_adminac_actor_i_6a531c_idx'), models.Index(fields=['-created'], name='ops_adminac_created_bbfb49_idx'), models.Index(fields=['action', '-created'], name='ops_adminac_action_c2e3f2_idx')],
            },
        ),
    ]
